name: first workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "wellcome blyat"
      - name: Print goodbye
        run: echo "see you again, Blyat"
    
